// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAUPsjnCFNYGTTn7sp9jARFkD_HpF-CDY',
    appId: '1:177358050271:web:e9cf28ea91cfa53b8eea6a',
    messagingSenderId: '177358050271',
    projectId: 'aiswarya-ledger',
    authDomain: 'aiswarya-ledger.firebaseapp.com',
    storageBucket: 'aiswarya-ledger.firebasestorage.app',
    measurementId: 'G-94SE1N7VJL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOI6pKUvZClb7pR_AcGkrh1wx00JTlre4',
    appId: '1:177358050271:android:73834ad53802ab5c8eea6a',
    messagingSenderId: '177358050271',
    projectId: 'aiswarya-ledger',
    storageBucket: 'aiswarya-ledger.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCQI9Gd5KhQEQcAOF47Sy6JUGJlFh-MF8M',
    appId: '1:177358050271:ios:d97e819aa47b8c528eea6a',
    messagingSenderId: '177358050271',
    projectId: 'aiswarya-ledger',
    storageBucket: 'aiswarya-ledger.firebasestorage.app',
    iosBundleId: 'com.example.ashgledger',
  );
}
